### ISSUE TITLE
Error when deploying Winter 18 Scratch Org

### ISSUE THREAD

**Issue by bijan-codescience** [muenzpraeger/salesforce-einstein-platform-apex#27]
We are getting the below error when pushing the code to scratch org with Winter 18:

ERROR:  Cannot read property 'getRepresentation' of undefined.

Stacktrace in the log:

"[ false,\n  '{\"message\":\"Cannot read property \\'getRepresentation\\' of undefined\",\"status\":1,\"stack\":\"TypeError: Cannot read property \\'getRepresentation\\' of undefined\\\\n    at AggregateSourceElement.composeMetadata (/Users/sfdx/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/aggregateSourceElement.js:395:48)\\\\n    at AggregateSourceElement.getFilePathTranslations (/Users/sfdx/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/aggregateSourceElement.js:353:35)\\\\n    at Promise.map.element (/Users/sfdx/.local/share/sfdx/client/node_modules/salesforce-alm/dist/lib/sourceConvertApi.js:114:42)\\\\n    at tryCatcher (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/util.js:16:23)\\\\n    at MappingPromiseArray._promiseFulfilled (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/map.js:61:38)\\\\n    at MappingPromiseArray.PromiseArray._iterate (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/promise_array.js:113:31)\\\\n    at MappingPromiseArray.init (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/promise_array.js:77:10)\\\\n    at MappingPromiseArray._asyncInit (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/map.js:30:10)\\\\n    at Async._drainQueue (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:143:12)\\\\n    at Async._drainQueues (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:148:10)\\\\n    at Immediate.Async.drainQueues (/Users/sfdx/.local/share/sfdx/client/node_modules/bluebird/js/release/async.js:17:14)\\\\n    at runCallback (timers.js:781:20)\\\\n    at tryOnImmediate (timers.js:743:5)\\\\n    at processImmediate [as _immediateCallback] (timers.js:714:5)\",\"name\":\"TypeError\",\"warnings\":[]}' ]"

**Comment by muenzpraeger** [comment]
I just deployed the current master without any issues. Which version of the Salesforce DX CLI are you using?

**Comment by bijan-codescience** [comment]
already on latest version: 6.0.9-3391781

**Comment by bijan-codescience** [comment]
Pulled the latest code and that fixed the issue.
