### ISSUE TITLE
Null exception from EinsteinDataset component

### ISSUE THREAD

**Issue by zaynelt** [muenzpraeger/salesforce-einstein-platform-apex#38]
If a user clicks into the 'Models' tab before actually training a model, the component throws an unhandled exception. 

[https://github.com/muenzpraeger/salesforce-einstein-platform-apex/blob/master/force-app/main/default/aura/EinsteinDataset/EinsteinDatasetHelper.js](url)
Line 26: `https://github.com/muenzpraeger/salesforce-einstein-platform-apex/blob/master/force-app/main/default/aura/EinsteinDataset/EinsteinDatasetHelper.js`

See fix: 
[https://github.com/muenzpraeger/salesforce-einstein-platform-apex/commit/6cfc5e827315377cf0084d95016c029940834b10](url)

**Comment by muenzpraeger** [comment]
Will be fixed in next release
