### ISSUE TITLE
metrics and learning curve response serialization

### ISSUE THREAD

**Issue by mshanemc** [muenzpraeger/salesforce-einstein-platform-apex#46]
Here's some of what I'm running into:

1. I can get back a response from all types
2. image learning curves are fine.  Metrics are fine for image and all language models
3. text return `epochResults` as `{}` and that causes an apex exception `FATAL_ERROR System.JSONException: Expected List<Einstein_EpochResult> but found { at [line:1, column:295]`
4. Like we discussed, you'll probably have to make a learning curve type 
5. model metrics (and probably LC) for image-multi-label are also broken in the parser
6. Then getModelMetrics and getModelLearningCurves in the Einstein_PredictionService probably need to be type-aware for their parsing issues (the other option would be to split them into type-specific methods, but I like that option less)
7.  Once those are done, I'll update my front-end for model-type-awareness

**Comment by muenzpraeger** [comment]
I'm considering to move the epoch results from a specific Apex class to an Object as the key in the JSON object is variable and cannot be parsed (see: 216.tennis-ball).

```
"epochResults": {
        "216.tennis-ball": [
          {
            "exampleName": "006_0034.jpg-basketball",
            "expectedLabel": "tennis-ball_negative",
            "predictedLabel": "tennis-ball_negative"
          },
```

**Comment by mshanemc** [comment]
YES!
