### ISSUE TITLE
Test cases are failing if the org has a namespace defined.

### ISSUE THREAD

**Issue by FishOfPrey** [muenzpraeger/salesforce-einstein-platform-apex#6]
Three of the test cases in Test_Einstein are failing if the org running the tests has a namespace defined.

1. Test_Einstein.testOtherMethods
1. Test_Einstein.trainDataset
1. Test_Einstein.createExamplesFromUrl

All are asserting that the Exception type will name is of an expected value. However, the presence of a namespace in the org alters the full type name.

You could change the assertions to use `instanceof`. 

```
        try {
            model = service.trainDataset(0, 'Beach and Mountain Model', 0, 0, '');
        } catch (Exception e) {
            System.debug('Error is: ' + e.getTypeName());
            System.assert(e instanceof Einstein_NoValuesException);
        }
```

Another alternative would be to only catch the expected exception type and fail anything else.

```
        try {
            model = service.trainDataset(0, 'Beach and Mountain Model', 0, 0, '');
            System.assert(false, 'Exception expected');
        } catch (Einstein_NoValuesException e) {
            System.debug('Error is: ' + e.getTypeName());
        }
```

**Comment by muenzpraeger** [comment]
The "instanceof" assertion makes IMHO more sense.
