### ISSUE TITLE
Unable to install in the developer edition 12 errors

### ISSUE THREAD

**Issue by archita6** [muenzpraeger/salesforce-einstein-platform-apex#60]
I am unable to deploy to a developer edition org . The org is basically a Trailhead playground . I tried in multiple orgs all have the same failure. Request your help. 

=== Component Failures [12]
TYPE   FILE                                                                                     NAME                                PROBLEM
─────  ───────────────────────────────────────────────────────────────────────────────────────  ──────────────────────────────────  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error  mdapi/profiles/Admin.profile                                                             Admin                               Unknown user permission: CreateWorkBadgeDefinition
Error  mdapi/aura/EinsteinDataAndTraining/EinsteinDataAndTraining.cmp                           EinsteinDataAndTraining             No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinDataAndTraining, markup://c:EinsteinDataset]
Error  mdapi/aura/EinsteinDataset/EinsteinDataset.cmp                                           EinsteinDataset                     No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinDataset]
Error  mdapi/aura/EinsteinDatasetCreation/EinsteinDatasetCreation.cmp                           EinsteinDatasetCreation             No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinDatasetCreation]
Error  mdapi/aura/EinsteinGenericPlaygroundComponent/EinsteinGenericPlaygroundComponent.cmp     EinsteinGenericPlaygroundComponent  No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinGenericPlaygroundComponent, markup://c:EinsteinDataAndTraining, markup://c:EinsteinDataset]
Error  mdapi/aura/EinsteinGenericPlaygroundComponent/EinsteinGenericPlaygroundComponent.design  EinsteinGenericPlaygroundComponent  No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinGenericPlaygroundComponent, markup://c:EinsteinGenericPlaygroundComponent, markup://c:EinsteinDataAndTraining, markup://c:EinsteinDataset]
Error  mdapi/aura/EinsteinLanguageModelBuilder/EinsteinLanguageModelBuilder.cmp                 EinsteinLanguageModelBuilder        No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinLanguageModelBuilder]
Error  mdapi/aura/einsteinModelMetrics/einsteinModelMetrics.cmp                                 einsteinModelMetrics                No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:einsteinModelMetrics]
Error  mdapi/aura/EinsteinModelSelect/EinsteinModelSelect.cmp                                   EinsteinModelSelect                 No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinModelSelect]
Error  mdapi/aura/EinsteinPlayground/EinsteinPlayground.cmp                                     EinsteinPlayground                  No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinPlayground, markup://c:EinsteinGenericPlaygroundComponent, markup://c:EinsteinDataAndTraining, markup://c:EinsteinDataset]
Error  mdapi/aura/EinsteinPredictionArea/EinsteinPredictionArea.cmp                             EinsteinPredictionArea              No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinPredictionArea]
Error  mdapi/aura/EinsteinUsage/EinsteinUsage.cmp                                               EinsteinUsage                       No COMPONENT named markup://c:LightningErrorHandler found : [markup://c:EinsteinUsage]

**Comment by muenzpraeger** [comment]
The LightningErrorHandler needs also to be installed. Either as package (https://github.com/mshanemc/LightningErrorHandler) or with metadata convert.

FYI @mshanemc - can you update the README in this repo to outline the best/needed steps? Thanks!
