### ISSUE TITLE
Cache API Token

### ISSUE THREAD

**Issue by mbrosseau** [muenzpraeger/salesforce-einstein-platform-apex#66]
Every time a request is made, the implementation actually does two calls; one to get an access token and a second to do the actual request. One could temporarily cache the token, say for an hour, reducing the volume of outbound API requests an improving performance.

**Comment by muenzpraeger** [comment]
Good call - will be implemented be end of this week.

**Comment by muenzpraeger** [comment]
This project gets archived, as it's functionality is now available on the [AppExchange](https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000Ed1V8UAJ).
