### ISSUE TITLE
Feature request: project packaging

### ISSUE THREAD

**Issue by pozil** [muenzpraeger/salesforce-einstein-platform-apex#67]
Could you consider packaging your project in order to make it easy to integrate into other projects as a dependency?

Right now, we have to deploy it to a scratch org and export/import it as metadata but this is time consuming and does not support versioning.
I would love to be able to install a specific version in a project with just one DX command:
`sfdx force:package:install -i 04xxxxxxxx`

Another extra nice-to-have feature would be to separate the core backend wrapper from the Playground UI to lighten up the project.

Pretty please 😍

**Comment by muenzpraeger** [comment]
UI and SDK are intentionally bound together. Packaging may be an option once DCP are GA.
