### ISSUE TITLE
Internal error occurs when email is not set in custom settings

### ISSUE THREAD

**Issue by pozil** [muenzpraeger/salesforce-einstein-platform-apex#68]
If you do not set your email in the custom settings, an internal error occurs as soon as you navigate to the *Playground* or *Einstein Usage* tab.

The error does not tell anything about what's wrong. May I suggest that you reinstate my previous contribution with the configuration checks that were reporting config errors?

![screen shot 2018-02-15 at 14 25 08](https://user-images.githubusercontent.com/5071767/36258815-6d3ef056-125c-11e8-8d40-6609d736605b.png)

**Comment by ankushsomani09** [comment]
Did you sign up to https://api.einstein.ai and downloaded the key. and upload that file in org. or either store in certificate management,

**Comment by pozil** [comment]
Thanks but I know what I did wrong. My point is that there should not be a
generic internal error, there should be a clear error message.

**Comment by muenzpraeger** [comment]
The previous check by @pozil only checked for file and email, while the current wrapper also includes very based with based on a key. It’s tricky to define the “correct” check (but feel free to contribute, it’s open source ;-)).

Having said that there may be a general change in the future - SAFE HARBOR - for how the auth mechanism is provided.

**Comment by muenzpraeger** [comment]
“cert based auth”, not “very based”, thank you autocorrect. ;-)
