### ISSUE TITLE
Don't have password of scratch org created using "SFDC Deploy"

### ISSUE THREAD

**Issue by ankushsomani09** [muenzpraeger/salesforce-einstein-platform-apex#69]
I clicked on "Deploy to SFDX", this created the scratch org and given the link to login to scratch org.
Now after one day i am trying to login to scratch org with given link, but can't. 
Trying to reset the password , then it ask  "What is your pet's name?"

Please help.

**Comment by muenzpraeger** [comment]
Please ask how to proceed on the project that provides the functionality. Thanks!

https://github.com/wadewegner/deploy-to-sfdx/issues
