### ISSUE TITLE
More descriptive errors

### ISSUE THREAD

**Issue by mbrosseau** [muenzpraeger/salesforce-einstein-platform-apex#71]
Often, when an exception occurs, an alert is sent that says "An internal server error has occurred".  For example, if one does not have access to the pem file or they put in the wrong email address.

Perhaps we could instead surface the actual error description, that way administrators don't need to sort through the logs.

**Comment by muenzpraeger** [comment]
This project gets archived, as it's functionality is now available on the [AppExchange](https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000Ed1V8UAJ).
