### ISSUE TITLE
how to store the private key in Certificate Management

### ISSUE THREAD

**Issue by bingwang0** [muenzpraeger/salesforce-einstein-platform-apex#76]
The Playground Intro tab says, "Store the certificate as certificate in the Certificate Management section of your org".  The private key file from Einstein.ai is in PEM format, and Certificate Management only takes JKS for import.  So I set about to do a conversion following this:
https://docs.oracle.com/cd/E35976_01/server.740/es_admin/src/tadm_ssl_convert_pem_to_jks.html
and got stuck on the step of importing CA cert - I don't really have one.  Am I doing this wrong?

**Comment by andyforandy** [comment]
Any luck with this issue?

**Comment by muenzpraeger** [comment]
This got removed in favor of a future, built-in solution.
