### ISSUE TITLE
Object detection fails with error "Bad request: modelType not supported for this endpoint" 

### ISSUE THREAD

**Issue by bingwang0** [muenzpraeger/salesforce-einstein-platform-apex#77]
I used the standard Alpine dataset and the sample picture from Einstein.ai
https://einstein.ai/products/custom-detection

??

**Comment by muenzpraeger** [comment]
Please provide the exact steps.

**Comment by bingwang0** [comment]
1.  create dataset and train model for Object Detection with https://einstein.ai/images/alpine.zip
2.  on Prediction tab under Object Detection, select "alpine model" as model, and use Image URL https://einstein.ai/images/alpine.jpg
3.  click Send.  Toast error message came up: "Error: Bad Request: modelType not supported for this endpoint"
screenshot: https://twitter.com/twtinc/status/981562722402914305
