### ISSUE TITLE
System.NoDataFoundException: Data Not Available

### ISSUE THREAD

**Issue by SfdcDeveloperAI** [muenzpraeger/salesforce-einstein-platform-apex#80]
I have created one Dev HUb org and deployed this code in it. I have created Einstein API account and downloaded my private key and done required changes in custom setting. Set org wide email id.

Now, I am going to Einstein Platform and started running the same but I am getting below error message:

System.NoDataFoundException: Data Not Available: The data you were trying to access could not be found. It may be due to another user deleting the data or a system error. If you know the data is not deleted but cannot access it, please look at our <A href="javascript:openPopupFocusEscapePounds('https://help.salesforce.com/apex/htdoor?body=%2Fhelp%2Fhlpsupportoptions_JP.jsp%3Ftssection%3Dsupport&loc=support&language=en_US&release=212.18.2&instance=CS6', 'Help', 1024, 768, 'width=1024,height=768,resizable=yes,toolbar=yes,status=yes,scrollbars=yes,menubar=yes,directories=no,location=yes,dependant=no', false, false);" title="support (New Window)">support</a> page.

Can you please help me in resolving the same?
Is there any particular step here which i am missing?
Also, if I generate token for my private key, how to apply that new one in this app? Or will it be programmed in such a way that it will pick automatically?

Please help asap on this.

Thanking in advance.
Best regards

**Comment by muenzpraeger** [comment]
Did you create a new Developer Edition? Or signed you up for a Salesforce DX Dev Hub? Those are different things.

Can you please provide the exact steps that lead to the error? Otherwise I'd have to guess.

The wrapper works in that way that it takes care of updating the token when you use the .pem. If you want to use a generated bearer token you can can pass it when creating a new Einstein_PredictionService object.
https://github.com/muenzpraeger/salesforce-einstein-platform-apex/blob/8862bf8668c433a9d4f7b417e607103b974016b3/force-app/main/default/classes/Einstein_PredictionService.cls#L50

**Comment by SfdcDeveloperAI** [comment]
Hello,

I have created new Dev Hub app using below link mentioned:

![image](https://user-images.githubusercontent.com/38833873/39409303-3a76b138-4c02-11e8-8dba-6ee0cb8c75ad.png)

I initially tried using creating Dev org but then code was not deployed into it. So, I just created new org.
Still, no luck whenever I clicked on image classification or any option it is prompting me the error message.

When I deployed code it gave me below link:
https://flow-business-9806-dev-ed.lightning.force.com/one/one.app#/setup/ApexDebugLogDetail/page?address=%2Fp%2Fsetup%2Flayout%2FApexDebugLogDetailEdit%2Fd%3Fapex_log_id%3D07LN000000kHdYKMA0%26retURL%3D%252Fsetup%252Fui%252FlistApexTraces.apexp%253FappLayout%253Dsetup%2526tour%253D%2526isdtp%253Dp1%2526sfdcIFrameOrigin%253Dhttps%25253A%25252F%25252Fflow-business-9806-dev-ed.lightning.force.com%2526nonce%253D1cb822c14ca27017b182621b8bf1fe3b479188c11ea1a3d37d929374e83bbc92%2526clc%253D1%2526sfdcIFrameHost%253Dweb

But no username, pwd is working which was there for my dev org.
Please help.

Thanks

**Comment by muenzpraeger** [comment]
This isn't an issue with the repo.

Please check the instructions in the section "Salesforce DX - deploy into developer edition or production org" for deploying the code to a Developer Edition.
