### ISSUE TITLE
Put the highest epoch onto the dataset's labelSummary

### ISSUE THREAD

**Issue by kowalewski230** [muenzpraeger/salesforce-einstein-platform-apex#90]
Put the best epoch onto the dataset's Summary.
On screen number 1,2 you will see mismatch between Summary f1 and Model Epoch 15 f1.
1.<img width="1272" alt="screen shot 2018-09-08 at 15 03 01" src="https://user-images.githubusercontent.com/17708914/45254463-e6893800-b378-11e8-8a43-0928aa0294e5.png">
2.<img width="1255" alt="screen shot 2018-09-08 at 15 02 45" src="https://user-images.githubusercontent.com/17708914/45254464-e6893800-b378-11e8-9207-ff399df80bdb.png">
Here is best apoch
3.<img width="1269" alt="screen shot 2018-09-08 at 15 07 42" src="https://user-images.githubusercontent.com/17708914/45254470-0d476e80-b379-11e8-9eb6-fc6508ec71e5.png">

**Comment by muenzpraeger** [comment]
This project gets archived, as it's functionality is now available on the [AppExchange](https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000Ed1V8UAJ).
