### ISSUE TITLE
Null pointer when change model typ in ptredictoin tab

### ISSUE THREAD

**Issue by kowalewski230** [muenzpraeger/salesforce-einstein-platform-apex#92]
Null pointer when change model type in prediction tab
Exception
<img width="1261" alt="screen shot 2018-09-09 at 14 16 55" src="https://user-images.githubusercontent.com/17708914/45264331-20227780-b43b-11e8-84e5-20df268b9345.png">

Steps to reproduce
<img width="1262" alt="screen shot 2018-09-09 at 14 16 45" src="https://user-images.githubusercontent.com/17708914/45264332-20227780-b43b-11e8-9b31-1c424c9d7127.png">
<img width="1260" alt="screen shot 2018-09-09 at 14 15 51" src="https://user-images.githubusercontent.com/17708914/45264333-20227780-b43b-11e8-891e-4d42fe0edc30.png">

**Comment by muenzpraeger** [comment]
This project gets archived, as it's functionality is now available on the [AppExchange](https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000Ed1V8UAJ).
