### ISSUE TITLE
An Internal Server has occured.

### ISSUE THREAD

**Issue by karanvenupure** [muenzpraeger/salesforce-einstein-platform-apex#94]
All configuration is done in SF org. When I accessing the Image Classification tab, that time I got the following error:

![image](https://user-images.githubusercontent.com/41714942/56789214-02195400-681f-11e9-8b14-0c644bba6162.png)

please help me to resolve this error.

**Comment by muenzpraeger** [comment]
That error is usually an indication that you attached the certificate file wrong. It's file name needs to end on `.pem`.

**Comment by karanvenupure** [comment]
Issues are resolved. It's occurred due to the certificate.

Thanks & Regards,

-----

Karan Venupure
Mo.No.:7972530549
Email Id: kvenupure@gmail.com
