### ISSUE TITLE
Installation error : pad block corrupted

### ISSUE THREAD

**Issue by mikuzz** [muenzpraeger/salesforce-einstein-platform-apex#96]
Hello,
during the installation process I got this error related to "pad blocked corrupted"
![image](https://user-images.githubusercontent.com/773043/57912515-c9ebbb00-788a-11e9-9f04-063c6c38e446.png)

1. My domain is active and published
2. Browser Crome
3. Environement : Dev Sandbox

**Comment by muenzpraeger** [comment]
Which installation process did you use?
-- 

*René Winkelmeyer*

+49 173 1682075

 muenzpraeger <https://github.com/muenzpraeger> |  muenzpraeger
<https://www.linkedin.com/in/muenzpraeger/> |  muenzpraeger
<https://twitter.com/muenzpraeger>

**Comment by muenzpraeger** [comment]
Which installation process did you use?

**Comment by mikuzz** [comment]
Tha package was installed from Appexchange and for all user (https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000Ed1V8UAJ)
I follow the documentation tha is here (https://quip.com/XOByAeXyuI21)

The key was generated with Salesforce login (I required a new one)

Email address of the user in Salesforce is the same that I use for the secret key and the same filled in the setup screen (Einstein Setup > Setup and configuration > Email address)

**Comment by muenzpraeger** [comment]
I forward that internally. The AppExchange app is based on this repo, but contains also modifications that are not here.

**Comment by mikuzz** [comment]
Thanks.
fyi: I arrive here because in the package installed via Appexchange there is this link.
![image](https://user-images.githubusercontent.com/773043/57940167-2de2a380-78cc-11e9-80c2-f9a352d363b7.png)

**Comment by muenzpraeger** [comment]
From what I heard back the error happens when you run the file upload/setup multiple times.

Can you please delete the custom settings for the app, and then upload the cert file again? Thanks.

**Comment by muenzpraeger** [comment]
This project gets archived, as it's functionality is now available on the [AppExchange](https://appexchange.salesforce.com/listingDetail?listingId=a0N3A00000Ed1V8UAJ).
