### ISSUE TITLE
API usage returning 'null'

### ISSUE THREAD

**Issue by aabrego** [muenzpraeger/salesforce-einstein-platform-apex#97]
When clicking on the *Einstein Admin* tab I see the following error:

![Screen Shot 2019-05-22 at 5 12 32 PM](https://user-images.githubusercontent.com/563784/58216807-d3bf5500-7cb4-11e9-8e8a-52712abb4b85.png)

I'm using the managed package version of the app, available [here](https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000Ed1V8UAJ):
Package Name: Einstein Playground
Version: Spring 2019 / 1.16.0
First Release: 4/9/2019
Latest Release: 4/10/2019

The _Intro_ page points to this repo. Is the latest version of managed package in sync with 'master' branch of this repo? 
![Screen Shot 2019-05-22 at 5 24 45 PM](https://user-images.githubusercontent.com/563784/58217200-87751480-7cb6-11e9-88c5-4fc19d56e181.png)

**Comment by muenzpraeger** [comment]
Thanks for reporting. I forwarded that info to the package owners. The underlying mechanics are taken from this repo, but there are modifications (as in the area where you see the error message), which aren't in here.

**Comment by surabhiiyer** [comment]
This is a known issue. Navigate to any of the predictions tab and try out a prediction. The error message will go away. Thanks!

**Comment by surabhiiyer** [comment]
FYI - you can try out some of the out of the box models that come with the package if you go to the Image Classification tab --> Predictions tab. Choose a classifier from the drop down list and upload an Image.
